### PR TITLE
Migrate V3.5.x to HPy 0.9.0

### PR DESCRIPTION
**Pull request by fangerer**
passes almost all tests on my machine:

```
8 failed, 6935 passed, 1539 skipped, 12 xfailed, 30 errors in 379.07s (0:06:19)
```

### CODE REVIEW

**Comment by mattip** [comment]
Is 30 errors similar to previous results?

**Comment by fangerer** [comment]
> Is 30 errors similar to previous results?

TBH, I don't know. These are the errors:
```
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_form_main_list - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_form_each_dict - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_form_dict_keys - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_baseline - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_bootstrapped - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_whiskers_float - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_whiskers_range - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_whiskers_percentiles - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_results_withlabels - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_label_error - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_bad_dims - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_boxplot_stats::test_boxplot_stats_autorange_false - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_complete[True] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_complete[False] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_disconnect[True] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_disconnect[False] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_wrong_disconnect[True] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_callback_wrong_disconnect[False] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_registration_on_non_empty_registry[True] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_registration_on_non_empty_registry[False] - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_cbook.py::Test_callback_registry::test_pickling - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_none - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_mean - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_mean_1d_base_slope_off_list_andor_axis0 - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_mean_2d - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_ValueError - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_mean_ValueError - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_linear - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_str_linear_1d - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
ERROR lib/matplotlib/tests/test_mlab.py::TestDetrend::test_detrend_linear_2d - pytest.PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
```

**Comment by mattip** [comment]
All those failures are due to using a too-new version of pytest, which errors on deprecated support for nose. Thanks @fangerer, merging

**Comment by fangerer** [comment]
Yeah, `v3.5.x` is more than a year old. Current version is `v3.7.x`. We should certainly update our branch. Not sure if I'll find the time.

**Pull request merged**
